### ISSUE TITLE
Full Functionality 18 buttons

### ISSUE THREAD

**Issue by alaenvargut** [JPZV/BluN64-ESP32#11]
Hey there, i´ve been looking for a way to convert my "PowerA" Switch controller from wired to wireless, I've read that one of the problems you have faced is the amount of "GPIO" the ESP32 owns, we can use a "Voltage Divider" to group some of them, I think it's not difficult, I have been doing this since i was an student, so I'll try to check all the code, and trying to adapt to this code

But here is an example of how to use a single GPIO to read 3 push buttons:

```

const int ledAzul = 2;
const int ledVerde = 3;
const int ledRojo = 4;
const int analogPin = A0;

void setup() {
  // Pines digitales en modo salida
  pinMode(ledAzul, OUTPUT);
  pinMode(ledVerde, OUTPUT);
  pinMode(ledRojo, OUTPUT);

  // Apaga todos los LEDs
  apagarLeds();

  // Inicia monitor serie
  Serial.begin(9600);
}

void loop() {
  // Leer el pin analógico
  int valorA0 = analogRead(analogPin);

  // Convertir a voltios el valor analógico
  float voltaje = valorA0 * (5.0/1023.0);

  // Mostramos los voltios en el monitor serie
  Serial.println(voltaje);

  // Apagamos LEDs
  apagarLeds();
  
  // Pulsador 1
  if(voltaje >= 1.25 && voltaje <2.5)
  {
    digitalWrite(ledAzul, HIGH);
  }
  // Pulsador 2
  else if(voltaje >= 2.5 && voltaje <3.75)
  {
    digitalWrite(ledVerde, HIGH);
  }
  // Pulsador 3
  else if(voltaje >= 3.75 && voltaje <=5)
  {
    digitalWrite(ledRojo, HIGH);
  }

  delay(100);
}

void apagarLeds()
{
  digitalWrite(ledAzul, LOW);
  digitalWrite(ledVerde, LOW);
  digitalWrite(ledRojo, LOW);
}



```
<img width="440" alt="Captura de pantalla 2023-12-10 a la(s) 10 18 40 p m" src="https://github.com/JPZV/BluN64-ESP32/assets/16258908/9de5e151-0218-4de9-983d-5ae9c15572c5">

<img width="474" alt="Captura de pantalla 2023-12-10 a la(s) 10 18 51 p m" src="https://github.com/JPZV/BluN64-ESP32/assets/16258908/a26ed7a1-e25c-47ce-95b5-091bd2d5052b">

![imagen](https://github.com/JPZV/BluN64-ESP32/assets/16258908/9a8dff55-d37d-461a-9856-018a76e5e9ee)

**Comment by JPZV** [comment]
That's a smart way to workaround the lack of GPIOs, though the "AnalogRead" homologous in ESP-IDF is a little hard to implement. Also, the project is just in standby mode while I release the BluControl, which will have support to MCP23017, and with that we can expand our GPIOs without losing any functionality (like being able to press all the keys at the same time for example, which I don't think we could do if we use Voltage Divider).

But thanks for the tip!!! I never thought about that!
