### ISSUE TITLE
Gyroscope with MPU6050

### ISSUE THREAD

**Issue by alaenvargut** [JPZV/BluN64-ESP32#12]
Is there any way to send Gyroscope data readed with MPU6050 sensor to Emulate NS Pro Controller gyroscope?

**Comment by JPZV** [comment]
I've never thought about the gyroscope to be honest.

Sadly, the [library](https://github.com/HandHeldLegend/HOJA-LIB-ESP32) that we use to connect to the NS doesn't seem to have support for gyroscope, and I'm not that pro (pun intended) to implement that.

If anyone is able to implement it into HOJA-LIB, then I'll try to implement it on my [fork](https://github.com/JPZV/HOJA-LIB-ESP32) and then in BluControl (but not in BluN64 though), but for now, I'll close this Issue.
