### ISSUE TITLE
Can not fully Clone repo: "/n64-switch /components/HOJA-LIB-ESP32 @ ca0ebc9" seems missing

### ISSUE THREAD

**Issue by marhalloweenvt** [JPZV/BluN64-ESP32#14]
Hello mate,
I would like to change pins layout and adopt it to newer ESP32-S3 (which is widely available in my local store) so I cloned this repo but it seems there are missing components: [**`/n64-switch /components/HOJA-LIB-ESP32 @ ca0ebc9`**](https://github.com/JPZV/BluN64-ESP32/tree/main/n64-switch/components)
Would you like to help me out with this issue?
Thank you for doing such a great work.

**Comment by JPZV** [comment]
Hi, thanks for reporting it. Now it should work correctly
